### ISSUE TITLE
小白请教一个问题，大佬勿喷...

### ISSUE THREAD

**Issue by DF-18** [Roujack/mathAI#17]
![微信截图_20200512231133](https://user-images.githubusercontent.com/65240237/81711271-11108a00-94a6-11ea-9e07-29b8b13e3de0.png)
我刚刚接触python，下载了你的程序，为什么test在运行的时候会报错呢

**Comment by Roujack** [comment]
你环境没有搭好，需要安装opencv的包。这个问题你应该先百度一下。

**Comment by DF-18** [comment]
谢谢您的回复，我弄好环境后，运行test.py出现以下错误，请问您知道是什么原因吗，找了好久没有找到原因
![image](https://user-images.githubusercontent.com/65240237/82165786-fa749380-98e8-11ea-8a98-7ac2d832c8b3.png)

**Comment by Roujack** [comment]
https://github.com/Roujack/mathAI/issues/5#issue-454631380
