### ISSUE TITLE
程序运行异常

### ISSUE THREAD

**Issue by xuyang5801** [Roujack/mathAI#3]
您好！
我对这个项目很感兴趣，采用文档中的接口模式运行，结果有如下报错：
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': './my_cnn_model_config5', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1c2d075748>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
Traceback (most recent call last):
  File "/Users/wuziyan/tensorflow/mathAI-master/系统代码(code)/test.py", line 3, in <module>
    save_filename = solver.solve('./testImgs/easy +/1.jpg')
  File "/Users/wuziyan/tensorflow/mathAI-master/系统代码(code)/solver/__init__.py", line 21, in solve
    symbols = binary_img_segment(binary_img, original_img)
  File "/Users/wuziyan/tensorflow/mathAI-master/系统代码(code)/tools/img_preprocess.py", line 68, in binary_img_segment
    img, contours, hierarchy = cv2.findContours(binary_img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)#cv2.RETR_TREE
ValueError: not enough values to unpack (expected 3, got 2)

Process finished with exit code 1

请教应如何配置才能正确运行？

**Comment by Roujack** [comment]
opencv-python版本是多少？测试版本3.4是OK的，超过4.0据说会报错。


------------------
罗文杰
中山大学


 




------------------ 原始邮件 ------------------
发件人: "xuyang5801"<notifications@github.com>;
发送时间: 2019年6月7日(星期五) 下午3:44
收件人: "Roujack/mathAI"<mathAI@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Roujack/mathAI] 程序运行异常 (#3)




您好！
 我对这个项目很感兴趣，采用文档中的接口模式运行，结果有如下报错：
 INFO:tensorflow:Using default config.
 INFO:tensorflow:Using config: {'_model_dir': './my_cnn_model_config5', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1c2d075748>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
 Traceback (most recent call last):
 File "/Users/wuziyan/tensorflow/mathAI-master/系统代码(code)/test.py", line 3, in 
 save_filename = solver.solve('./testImgs/easy +/1.jpg')
 File "/Users/wuziyan/tensorflow/mathAI-master/系统代码(code)/solver/init.py", line 21, in solve
 symbols = binary_img_segment(binary_img, original_img)
 File "/Users/wuziyan/tensorflow/mathAI-master/系统代码(code)/tools/img_preprocess.py", line 68, in binary_img_segment
 img, contours, hierarchy = cv2.findContours(binary_img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)#cv2.RETR_TREE
 ValueError: not enough values to unpack (expected 3, got 2)
 
Process finished with exit code 1
 
请教应如何配置才能正确运行？

**Comment by xuyang5801** [comment]
4.1版本的
