### ISSUE TITLE
Program KeyError

### ISSUE THREAD

**Issue by TYoung1221** [Roujack/mathAI#4]
您好，当我输入例子，例如example/2.jpg，example/5.jpg，和hard下的例子，都会报一个status错误。
`     68     # print(parser_tree)
     69     set_forward_step(0)
---> 70     post_order(parser_tree)
     71     y_start = 0.9
     72     y_stride = 0.2

~/Desktop/dino/mathAI/code/calculator/__init__.py in post_order(node)
    275         elif node['type'] == NODE_TYPE['e']:
    276             # print('post_order e')
--> 277             t = post_order(child[0])
    278             node['status'] = child[0]['status']
    279             node['value'] = child[0]['value']

~/Desktop/dino/mathAI/code/calculator/__init__.py in post_order(node)
    199             # print('post_order t',child[0])
    200             f = post_order(child[0])
--> 201             node['status'] = child[0]['status']
    202             node['value'] = child[0]['value']
    203             latex_str = f

KeyError: 'status'
`

**Comment by Roujack** [comment]
你好，现在只能跑简单版本的加减乘数运算，复杂的不公开。
