### ISSUE TITLE
.py函数调用出错

### ISSUE THREAD

**Issue by canvas-J** [Roujack/mathAI#5]
试运行，发现parser的characters_to_nodes函数无法调用到，也无法按照from xx import xx，抑或import xx.xx，删除该文件夹并另存__init__为.py仍旧没解决问题，不只是为何？

**Comment by canvas-J** [comment]
报错信息如下：
    File "c:\Users\xx\Documents\Repository\mathAI\系统代码(code)\welcome.py", line 41, in upload_file
    result_file = solver.solve(save_file_path)
    File "c:\Users\xx\Documents\Repository\mathAI\系统代码(code)\solver\__init__.py", line 65, in solve
    node_list = parser.characters_to_nodes(characters)
    AttributeError: module 'parser' has no attribute 'characters_to_nodes'

**Comment by Roujack** [comment]
你好，据说是parser跟TensorFlow还是windows系统命名冲突了，请你修改本项目的parser命名，改成其它名字，然后调用到的地方也改成对应名字。

**Comment by xiaobaisheni** [comment]
怎么发到这里来了？


 
---原始邮件---
发件人: "biu_lige_biu"<notifications@github.com>
发送时间: 2019年6月11日(星期二) 晚上7:21
收件人: "Roujack/mathAI"<mathAI@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Roujack/mathAI] .py函数调用出错 (#5)



试运行，发现parser的characters_to_nodes函数无法调用到，也无法按照from xx import xx，抑或import xx.xx，删除该文件夹并另存__init__为.py仍旧没解决问题，不只是为何？

**Comment by canvas-J** [comment]
谢谢，的确是这个问题

**Comment by DF-18** [comment]
> 你好，据说是parser跟TensorFlow还是windows系统命名冲突了，请你修改本项目的parser命名，改成其它名字，然后调用到的地方也改成对应名字。

您好，我改了parser的名称（import parser as psr），引用parser的地方也都改成了psr，但运行还是报同样的错
报错如下：
Traceback (most recent call last):
  File "E:/PY location/test.py", line 3, in <module>
    save_filename = solver.solve('./testImgs/easy +/3.jpg')
  File "E:\PY location\solver\__init__.py", line 65, in solve
    node_list = psr.characters_to_nodes(characters)
AttributeError: module 'parser' has no attribute 'characters_to_nodes'

**Comment by Roujack** [comment]
> > 你好，据说是parser跟TensorFlow还是windows系统命名冲突了，请你修改本项目的parser命名，改成其它名字，然后调用到的地方也改成对应名字。
> 
> 您好，我改了parser的名称（import parser as psr），引用parser的地方也都改成了psr，但运行还是报同样的错
> 报错如下：
> Traceback (most recent call last):
> File "E:/PY location/test.py", line 3, in
> save_filename = solver.solve('./testImgs/easy +/3.jpg')
> File "E:\PY location\solver__init__.py", line 65, in solve
> node_list = psr.characters_to_nodes(characters)
> AttributeError: module 'parser' has no attribute 'characters_to_nodes'

我觉得应该修改parser的文件名为psr，然后import psr试试看？

**Comment by Roujack** [comment]
这个问题太多人遇到了，我试试把parser改掉看看吧。

**Comment by DF-18** [comment]
> 这个问题太多人遇到了，我试试把parser改掉看看吧。

如果这样能解决问题那太好啦，辛苦您啦
